### PR TITLE
Add tooltips

### PR DESCRIPTION
**Pull request by leha-code**

### CODE REVIEW

**Comment by leha-code** [comment]
I couldn't add tooltips to the two last tabs

**Comment by leha-code** [comment]
Wait don't merge yet, I'll add the rest...

**Comment by TheBrokenRail** [comment]
Ah yes, the world name text box is made of world name. What benefit does this add apart from cluttering the interface?

**Comment by TheBrokenRail** [comment]
Ah yes, the world name text box is made of world name. What benefit does this add apart from cluttering the interface?

**Comment by TheBrokenRail** [comment]
I'm just going to close this.

**Pull request closed without merging**
